### ISSUE TITLE
Not work in Nuxt v3.6.2

### ISSUE THREAD

**Issue by howard-tzw** [antfu/vscode-goto-alias#11]
### Describe the bug

In my macOS environment, while using vscode with Nuxt 3.6.2, when I press "opt" and click on a component, VSCode displays two definitions: one from `components.d.ts` and the other from the source of that component. It fails to correctly navigate to the file location of the component with this extension.

### Reproduction

skip

### System Info

```Shell
System:
    OS: macOS 13.2
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
    Memory: 7.06 GB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.14.2 - ~/.nvm/versions/node/v18.14.2/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v18.14.2/bin/yarn
    npm: 9.5.0 - ~/.nvm/versions/node/v18.14.2/bin/npm
    pnpm: 8.5.0 - ~/.nvm/versions/node/v18.14.2/bin/pnpm
  Browsers:
    Chrome: 114.0.5735.198
    Safari: 16.3
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by lsimone** [comment]
the same happens to me.

**Comment by lsimone** [comment]
> @lsimone @howard-tzw
> 
> Does v0.1.5+ solve your problem?

@ShenQingchuan I can confirm `v0.1.5`  works for me now, thanks!

**Comment by taily-khucnaykhongquantrong** [comment]
> @lsimone @howard-tzw
> 
> Does v0.1.5+ solve your problem?

I am using v0.1.6 and it is not working on my Nuxt v3.10.0. I have enabled `takeover` mode and tried using `node_modules` typescript version.
<img width="745" alt="image" src="https://github.com/antfu/vscode-goto-alias/assets/9252925/728d2a3f-8cee-421d-ad1d-5913a36579ac">
