### ISSUE TITLE
v 0.2.0 broken on windows 11 vscode 1.94.2, unlimited loading or stuck

### ISSUE THREAD

**Issue by dickofn** [antfu/vscode-goto-alias#23]
### Describe the bug

1. you jump (ctrl+click) to a custom component, 
2. works just fine, 
3. close that tab,
4. jump to the same component

Now there is a loading bar moving just below the tab, everything looks just fine.
But nope, IntelliSense is not working after that

### Reproduction

go to a component, close, go to same component again

### System Info

```Shell
System:
    OS: Windows 11 10.0.22631
    CPU: (16) x64 AMD Ryzen 7 5800X 8-Core Processor
    Memory: 8.92 GB / 31.93 GB
  Binaries:
    Node: 20.11.0 - ~\AppData\Local\fnm_multishells\40828_1730177969014\node.EXE
    Yarn: 1.22.21 - ~\AppData\Local\fnm_multishells\40828_1730177969014\yarn.CMD
    npm: 10.2.4 - ~\AppData\Local\fnm_multishells\40828_1730177969014\npm.CMD
    pnpm: 8.14.1 - ~\AppData\Local\fnm_multishells\40828_1730177969014\pnpm.CMD
  Browsers:
    Edge: Chromium (127.0.2651.74)
    Internet Explorer: 11.0.22621.3527
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by rylanharper** [comment]
^^ Same on Mac OS for this. Had to uninstall the plugin 😢

**Comment by dickofn** [comment]
> ^^ Same on Mac OS for this. Had to uninstall the plugin 😢

@rylanharper for now you can just choose "Install another version" options when clicking gear icon, and pick 0.18.0

**Comment by antfu** [comment]
Can anyone share a reproduction?

/cc @Donovan-Ye are you aware of this? Could you help to take a look? Thank you

**Comment by cheny-github** [comment]
I got same problem too

**Comment by arcovery** [comment]
I got same problem too

**Comment by Donovan-Ye** [comment]
> Can anyone share a reproduction?
> 
> /cc @Donovan-Ye are you aware of this? Could you help to take a look? Thank you

👌 I am looking at this issue now.

**Comment by Donovan-Ye** [comment]
@rylanharper Could you provide a minimal reproduction on macOS? I am unable to replicate the issue on my Mac running macOS 14.2 and vscode 1.95.0. I will attempt to downgrade my vscode version first.

**Comment by Donovan-Ye** [comment]
@rylanharper Could you please provide a minimal reproduction in MacOS? I am unable to replicate this issue on my Mac with MacOS 14.2 and VSCode 1.95.0. I will attempt to downgrade my VSCode version to resolve it.

**Comment by Donovan-Ye** [comment]
> @rylanharper Could you please provide a minimal reproduction in MacOS? I am unable to replicate this issue on my Mac with MacOS 14.2 and VSCode 1.95.0. I will attempt to downgrade my VSCode version to resolve it.

After downgrading vscode to version 1.94.2 on my macOS, I am still unable to reproduce the issue with plugin v0.2.0 and [vitesse](https://github.com/antfu-collective/vitesse)...

**Comment by dickofn** [comment]
Fyi I'm using nuxt 3, but currently on holiday, not with my machine

**Comment by Donovan-Ye** [comment]
I will try again later with more complex projects.

**Comment by rylanharper** [comment]
For some reason, now that I have re-installed the plugin, I'm not getting the unlimited loading like I was (even though I'm working on the same project).. Trying to replicate this again..

**Comment by Donovan-Ye** [comment]
After trying several times, I discovered that when I reload VSCode and use command+click to go to the definition, it sometimes shows "loading progress" under the tab. This happens because TypeScript needs time to resolve the code in my cases. But rarely encountered.

For the minimal reproduction, I think which is the simplest code that consistently triggers the bug.

**Comment by dtrongphuc** [comment]
Same on my Mac

**Comment by Donovan-Ye** [comment]
> Same on my Mac

@dtrongphuc Can you find which plugin or process is loading? and you can try reinstalling the plugin to see if that fixes it.

**Comment by dickofn** [comment]
> After trying several times, I discovered that when I reload VSCode and use command+click to go to the definition, it sometimes shows "loading progress" under the tab. This happens because TypeScript needs time to resolve the code in my cases. But rarely encountered.
> 
> For the minimal reproduction, I think which is the simplest code that consistently triggers the bug.

I can somewhat confirm this since, my project is right now considerably minimal

**Comment by Donovan-Ye** [comment]
> > After trying several times, I discovered that when I reload VSCode and use command+click to go to the definition, it sometimes shows "loading progress" under the tab. This happens because TypeScript needs time to resolve the code in my cases. But rarely encountered.
> > For the minimal reproduction, I think which is the simplest code that consistently triggers the bug.
> 
> I can somewhat confirm this since, my project is right now considerably minimal

Could you please share your code with me so I can investigate further the issue? with github, sandbox or any other ways.

**Comment by dtrongphuc** [comment]
@Donovan-Ye This issue occasionally appears around 30 minutes to 1 hour after I start working in VSCode. In my case, I'm working on a file with several components, and `Cmd + Click` works well initially. However, when I open another file that also has components, `Cmd + Click` gets stuck, and CPU usage increases to 80% - 90%.

Just disable the extension, and I haven't seen this issue again.

<img width="356" alt="image" src="https://github.com/user-attachments/assets/f30a5ae7-eca3-4fbb-b450-3f63af7a8517">

<img width="1753" alt="image" src="https://github.com/user-attachments/assets/7f0c91ae-8dda-46f8-82dc-65751b86dff0">

**Comment by Donovan-Ye** [comment]
<img width="564" alt="image" src="https://github.com/user-attachments/assets/d52dcbf7-694d-458a-82d0-0e693bc71960">

Yes, this issue occurs occasionally. Version 0.2.0 might trigger it when working with another plugin. I will investigate further. Thank you!

**Comment by s3xysteak** [comment]
It seems to be a race condition issue. Assume we trigger `provideDefinition` twice almost in the same time - let's call it A and B:

First, set `triggerDoc = A.doc` and `triggerPos = A.pos`. Almost simultaneously, this state also occurs for B. As a result, it enters a cycle: when the state is A, the recursive state becomes B, which means both of them can't be caught by the // prevent infinite loop and reduce unnecessary calls statement.

To repro it, we can add a delay manually(This also shows that the problem usually occurs on machines with worse performance):

```ts
function sleep(ms: number) {
  return new Promise(res => setTimeout(res, ms))
}
```

Add the code here: https://github.com/antfu/vscode-goto-alias/blob/main/src/index.ts#L48

```ts
triggerPos = position

console.log('hi') // for test
await sleep(500)
```

Use any code like:

```ts
const one = 1
const two = 2
```

Hold down ctrl and move the mouse back and forth between the two of them. On my computer this can stably reproduce the issue.

To fix it, I think use `WeakSet` to store current instance may be a good solution.

**Comment by dickofn** [comment]
> > > After trying several times, I discovered that when I reload VSCode and use command+click to go to the definition, it sometimes shows "loading progress" under the tab. This happens because TypeScript needs time to resolve the code in my cases. But rarely encountered.
> > > For the minimal reproduction, I think which is the simplest code that consistently triggers the bug.
> > 
> > 
> > I can somewhat confirm this since, my project is right now considerably minimal
> 
> Could you please share your code with me so I can investigate further the issue? with github, sandbox or any other ways.

really sorry this project is internal only, I also can confirm other people reply about high CPU usage after the infinite loading start

**Comment by Donovan-Ye** [comment]
> It seems to be a race condition issue. Assume we trigger `provideDefinition` twice almost in the same time - let's call it A and B:
> 
> First, set `triggerDoc = A.doc` and `triggerPos = A.pos`. Almost simultaneously, this state also occurs for B. As a result, it enters a cycle: when the state is A, the recursive state becomes B, which means both of them can't be caught by `// prevent infinite loop and reduce unnecessary calls statement`.
> 
> To repro it, we can add a delay manually(This also shows that the problem usually occurs on machines with worse performance):
> 
> ```ts
> function sleep(ms: number) {
>   return new Promise(res => setTimeout(res, ms))
> }
> ```
> 
> Add the code here: https://github.com/antfu/vscode-goto-alias/blob/main/src/index.ts#L48
> 
> ```ts
> triggerPos = position
> 
> console.log('hi') // for test
> await sleep(500)
> ```
> 
> Use any code like:
> 
> ```ts
> const one = 1
> const two = 2
> ```
> 
> Hold down ctrl and move the mouse back and forth between the two of them. On my computer this can stably reproduce the issue.
> 
> To fix it, I think use `WeakSet` to store current instance may be a good solution.

Excellent! I will give it a try and make the necessary corrections as soon as possible.

**Comment by Donovan-Ye** [comment]
@s3xysteak Thank you for your inspiration! It was indeed caused by a race condition.

Initially, I attempted to add a WeakSet. However, if it is not cleaned properly, subsequent attempts to control+click on the definition will fail to navigate to the intended location.

And I found even if the `provideDefinition` function of goto-alias returns null, VSCode will still execute other `provideDefinition` functions by default. Therefore, I believe it just need to to implement a locking mechanism while one goto-alias' `provideDefinition` function is running and remove the lock once it has finished.

**Comment by dickofn** [comment]
> Please upgrade to version 0.2.1. If the issue still happens, please respond here~

Now works better, there is no stuck at all but with a new problem on my side.

Sometimes it perfectly goes to the definition, but sometimes it goes to `.nuxt\components.d.ts` instead

It's unimportant, but I just put it here for your information.

**Comment by dickofn** [comment]
> ok~ I will fix it later.

Thanks a lot @Donovan-Ye it really improves my coding experience with Nuxt, cheers 🥂
