### ISSUE TITLE
Ends up to (最终停在了) shims.d.ts 

### ISSUE THREAD

**Issue by grandsong** [antfu/vscode-goto-alias#3]
### Describe the bug

I created a project based on Vitesse Lite, installed this extension and it worked well.
But recently, after I updated Volar (which is 1.0.3) and all NPM packages, this extension on longer works as expected.
Now, if I alt+click a component in a .vue SFC, VS Code opens a tab for "components.d.ts" and immediatly opens another for "shims.d.ts" and ends up there.

---
I read https://github.com/antfu/unplugin-vue-components/issues/177
So I checked ".npmrc", "shamefully-hoist=true" remains as it was.
I also added @vue/runtime-core to devDependencies. No luck.
I disabled this extension, or moved "shims.d.ts", either way, clicks ended up to "components.d.ts". So, the two are still necessary.
I don't know what else I could try.

---
### the minimal reproduction
I just use Vitesse Lite template on GitHub to create one repo.
Then, I updated all NPM packages.
I tried clicking <Footer> in  App.vue. This issue can be reproduced.

### Reproduction

https://github.com/grandsong/reproduction

### System Info

```Shell
System:
    OS: Windows 10 10.0.19044
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
    Memory: 1.65 GB / 15.84 GB
  Binaries:
    Node: 16.17.0 - C:\Env\node\node.EXE
    npm: 7.9.0 - C:\Env\node\npm.CMD
  Browsers:
    Edge: Spartan (44.19041.1266.0), Chromium (106.0.1370.42)
    Internet Explorer: 11.0.19041.1566
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by VoVAllen** [comment]
Same problem

**Comment by grandsong** [comment]
I have followed the instructions and disabled VS Code built-in TypeScript. But I still ends up with "shims.d.ts". 
I have also checked settings where volar.takeOverMode.enabled is "auto".

**Comment by loktarjugg** [comment]
same here
I am using vitesse, and I'm pretty sure the configuration is correct. but it still points to `components.d.ts`
