### ISSUE TITLE
Close components.d.ts when auto opening a component.

### ISSUE THREAD

**Issue by vanling** [antfu/vscode-goto-alias#5]
### Clear and concise description of the problem

This extension is awesome and I think im at a point in my life that i can not live without it. 
What would make it better is to not leave the `components.d.ts` file open after switching to the correct alias/file.

I was hoping `"workbench.editor.enablePreviewFromQuickOpen": true` would work, but its actually opening the .d.ts files so no luck there.

### Suggested solution

I am not sure if possible in vscode but some way to "close the previous file" and i can imagine some people love that it stays open so could be a configurable feature?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Livan-pro** [comment]
FYI. It's available by setting `"gotoAlias.closeDts": true`.

**Comment by vanling** [comment]
Yes thanks, it works :)
