### ISSUE TITLE
Not working in Nuxt3

### ISSUE THREAD

**Issue by howard-tzw** [antfu/vscode-goto-alias#6]
### Describe the bug

In a default nuxt3 project, it seems to be not working and just redirect to `.nuxt/components.d.ts`..

### Reproduction

(skip)

### System Info

```Shell
(skip)
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by joel-wenzel** [comment]
I am seeing similar behavior on nuxt3, though it was working for me on nuxt3 briefly when I started a new project. It doesn't seem to anymore though. I have takeover mode enabled on volar.

I created a brand new nuxt3 project just to see and it seemed like that had the same issue

**Comment by Ragura** [comment]
This is not exclusive to Nuxt. It also happens in our (larger) project. We simply end up in the `components.d.ts` file with no redirect.

**Comment by shamscorner** [comment]
It is not working for me as well. It just redirects to `components.d.ts` every time.

Also would be better if it doesn't open the `components.d.ts` file at all, only redirects to that specific file.

**Comment by lautr** [comment]
Having the same Issue with my Nuxt + Storybook Monorepo, happens in both packages - it opens the `*.d.ts` file but doesn't open the `*.vue` file afterwards:

https://github.com/lautr/initium-nuxt

**Comment by ascott18** [comment]
This extension doesn't work at all for me, but https://marketplace.visualstudio.com/items?itemName=dariofuzinato.vue-peek works great

**Comment by ascott18** [comment]
Opened a PR #7 that should fix this extension not working.
